In [ ]:
import pandas as pd
import requests

In [5]:
response = requests.get("https://goodrecmovies.com/api/list?kind=movie&pageSize=10")

In [10]:
df = pd.DataFrame(response.json()['rows'])[['startYear','adult','avgRating','votes','rank']]

   startYear  adult  avgRating    votes  rank
0       1972  False        9.2  2268012     1
1       1957  False        9.0  1009497     2
2       1994  False        9.3  3257493     3
3       1993  False        9.0  1610733     4
4       2008  False        9.1  3243566     5
5       2003  False        9.0  2203703     6
6       1974  False        9.0  1521068     7
7       2001  False        8.9  2247753     8
8       1966  False        8.8   905350     9
9       1994  False        8.8  2478983    10

In [16]:
df = pd.DataFrame()

In [ ]:
for i in range(0,349):
    response = requests.get(f"https://goodrecmovies.com/api/list?kind=movie&pageSize=10&page={i}")
    temp_df = pd.DataFrame(response.json()['rows'])[['startYear','adult','avgRating','votes','rank']]
    df = pd.concat([df,temp_df],ignore_index=True)
print("Success full")

In [21]:
df.head

<bound method NDFrame.head of       startYear  adult  avgRating    votes  rank
0          1972  False        9.2  2268352     1
1          2026  False        9.3    16228     2
2          1957  False        9.0  1009660     3
3          1994  False        9.3  3257990     4
4          1993  False        9.0  1610975     5
...         ...    ...        ...      ...   ...
3475       2003  False        7.1    32892  3476
3476       2022  False        7.1    31277  3477
3477       2000  False        7.1    38095  3478
3478       2004  False        7.1    45697  3479
3479       2018  False        7.1   144234  3480

[3480 rows x 5 columns]>

In [22]:
df

      startYear  adult  avgRating    votes  rank
0          1972  False        9.2  2268352     1
1          2026  False        9.3    16228     2
2          1957  False        9.0  1009660     3
3          1994  False        9.3  3257990     4
4          1993  False        9.0  1610975     5
...         ...    ...        ...      ...   ...
3475       2003  False        7.1    32892  3476
3476       2022  False        7.1    31277  3477
3477       2000  False        7.1    38095  3478
3478       2004  False        7.1    45697  3479
3479       2018  False        7.1   144234  3480

[3480 rows x 5 columns]

In [24]:
df.to_csv("Movie.csv")